name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 2.0.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  meta: ^1.15.0
  gherkin: ^3.1.0
  # gherkin:
  #   path: ../dart_gherkin

dev_dependencies:
  test: ^1.25.8
  pedantic: ^1.11.1
