name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.17
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ^6.11.0
  collection: ^1.19.0
  gherkin: ^3.1.0
  source_gen: ^1.1.1
  build: ^2.4.1
  glob: ^2.1.2

dev_dependencies:
  pedantic: ^1.11.1
  build_config: ^1.0.0
  flutter_lints: ^5.0.0
